Support for UTF-8 content. Hebrew import now preserve encoding
wimsymons/intellij-ppimport pull request #10
Opened 2017-01-11 08:34 UTC by eliagrady

I don't know why, but 'CharStreams.copy(reader, writer)' would kill the UTF-8 hebrew encoding.
What I've done is to detect UTF-8 and bypass the copy method with raw byte copy.
Hebrew characters are now preserved via 'import'.

2017-01-22 20:03 UTC, wimsymons commented on src/main/be/wimsymons/intellij/polopolyimport/PPImporter.java
> +    InputStream stream = new ReaderInputStream(reader, "UTF-8");
Why not use https://docs.oracle.com/javase/7/docs/api/java/io/InputStreamReader.html?

2017-01-22 20:05 UTC, wimsymons commented on src/main/be/wimsymons/intellij/polopolyimport/PPImporter.java
> +      if(contentType.contains("UTF-8")) {
Shouldn't you do case-insensitive matching to be sure?

2017-01-22 20:07 UTC, wimsymons commented on src/main/be/wimsymons/intellij/polopolyimport/PPImporter.java
> +				String contentType = "text/xml&charset=" + virtualFile.getCharset();
The '&' is wrong. Check https://www.w3.org/Protocols/rfc1341/4_Content-Type.html. It must be a ';'. Maybe a typo?

2017-01-22 20:08 UTC, wimsymons requested changes
Some things don't seem correct. Can you check my comments and fix them?

2017-01-22 20:11 UTC, wimsymons commented
Other question for you Elia. I no longer use Polopoly at work as a CMS so supporting this plugin is no longer of my interest. You be willing to become the new owner of the code?

2017-01-23 10:36 UTC, eliagrady commented on src/main/be/wimsymons/intellij/polopolyimport/PPImporter.java
> +    InputStream stream = new ReaderInputStream(reader, "UTF-8");
The one you've suggested extended Reader.
The one I'm using extends InputStream.
Basically, I've used it in order to get access to the InputStream, that was previously wrapped with a Reader, while not changing the API to pass it down.
Both support the 'read(byte[] b, int off, int len)' call, but the ReaderInputStream also supports 'read(byte[] b)' which InputStreamReader does not.

2017-01-23 10:38 UTC, eliagrady commented on src/main/be/wimsymons/intellij/polopolyimport/PPImporter.java
> +      if(contentType.contains("UTF-8")) {
yes, you're right. 
contentType.toLowerCase().contains("utf-8") should be better.

2017-01-23 10:42 UTC, eliagrady commented on src/main/be/wimsymons/intellij/polopolyimport/PPImporter.java
> +				String contentType = "text/xml&charset=" + virtualFile.getCharset();
Not a typo.
Some history: the eclipse plugin was working just fine and I was trying to imitate its behavior.
As you can see at line 20 here:
https://github.com/jwiklund/pp-eclipse/blob/master/src/pp/eclipse/post/ContentImporter.java
They used &.
I should test it further to see if it's some weird implementation artifact from the ATEX importer internal code, or stick with the W3C spec.

2017-01-23 10:43 UTC, eliagrady commented
Regarding code ownership, as long as I work with the Atex system - sure - no problem.

2017-04-21 21:25 UTC, merged